### ISSUE TITLE
Format Document is analyzing entire VS code folder

### ISSUE THREAD

**Issue by cristianburca** [nvuillam/vscode-groovy-lint#141]
Hello and nice to use your extension. 

I have a quick question. 
I'm using 'Format Document' using this groovy linting extension and after some time it starts analying my entire folder (The size is quite big and the vs code performance degrades). How do I stop analyzing everything and lint only Opened File Only in VSCode?

This is running from minutes ago.
![image](https://user-images.githubusercontent.com/24667632/150343247-730629d4-393e-47de-9d4a-83c7982376d4.png)

**Comment by nvuillam** [comment]
Npm-groovy-lint can sometimes be performance onsuming on small computers 

Please can you share what is in the GroovyLint output panel ?

![image](https://user-images.githubusercontent.com/17500430/150641566-c42d0e08-05fa-4249-b9e4-d11de0ba44e2.png)

**Comment by cristianburca** [comment]
Thanks @nvuillam for picking up this. Maybe this would be helpful?

`(node:15300) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.parseLinterResults (d:\Users\cburca\.vscode\extensions\nicolasvuillamy.vscode-groovy-lint-1.7.4\server\out\linterParser.js:14:61)
    at Object.<anonymous> (d:\Users\cburca\.vscode\extensions\nicolasvuillamy.vscode-groovy-lint-1.7.4\server\out\linter.js:259:61)
    at Generator.next (<anonymous>)
    at fulfilled (d:\Users\cburca\.vscode\extensions\nicolasvuillamy.vscode-groovy-lint-1.7.4\server\out\linter.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:15300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1064)
Start analyzing file:///d%3A//git//Stages/tttt.groovy`

**Comment by nvuillam** [comment]
@cristianburca I can not reproduce but I may found a way to solve the issue, please can you check with version 1.7.5 and provide feedback ?

**Comment by cristianburca** [comment]
Trying right now

**Comment by cristianburca** [comment]
This is mostly what I see in the logs. the question remains, why it analyzes everything and not just the file I want to format? My Jenkins DSL project is quite big and VS code performance is impacted.

`CodeNarcServer unexpected error:
{
  "message": "Request failed with status code 500",
  "name": "Error",
  "stack": "Error: Request failed with status code 500\n    at createError (d:\\Users\\cburca\\.vscode\\extensions\\nicolasvuillamy.vscode-groovy-lint-1.7.5\\server\\node_modules\\axios\\lib\\core\\createError.js:16:15)\n    at settle (d:\\Users\\cburca\\.vscode\\extensions\\nicolasvuillamy.vscode-groovy-lint-1.7.5\\server\\node_modules\\axios\\lib\\core\\settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (d:\\Users\\cburca\\.vscode\\extensions\\nicolasvuillamy.vscode-groovy-lint-1.7.5\\server\\node_modules\\axios\\lib\\adapters\\http.js:269:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "config": {
    "url": "http://localhost:7484/request",
    "method": "post",`
    
    
   `Unable to use CodeNarc JSON result
 {"err":"Unable to parse CodeNarc completed: (p1=1; p2=2; p3=9) 1332ms\r\n"}`
 
 `GroovyLint: Request cancelled by duplicate call on requestKey d:\git\DevOps\shared-lib\vars\test.groovy-none
[Info  - 17:30:05] Connection to server got closed. Server will restart.
[Error - 17:30:05] Request workspace/executeCommand failed.
Error: Connection got disposed.
    at Object.dispose (d:\Users\cburca\.vscode\extensions\nicolasvuillamy.vscode-groovy-lint-1.7.5\client\node_modules\vscode-jsonrpc\lib\main.js:904:25)
    at Object.dispose (d:\Users\cburca\.vscode\extensions\nicolasvuillamy.vscode-groovy-lint-1.7.5\client\node_modules\vscode-languageclient\lib\client.js:74:35)
    at LanguageClient.handleConnectionClosed (d:\Users\cburca\.vscode\extensions\nicolasvuillamy.vscode-groovy-lint-1.7.5\client\node_modules\vscode-languageclient\lib\client.js:2309:42)
    at LanguageClient.handleConnectionClosed (d:\Users\cburca\.vscode\extensions\nicolasvuillamy.vscode-groovy-lint-1.7.5\client\node_modules\vscode-languageclient\lib\main.js:155:15)
    at closeHandler (d:\Users\cburca\.vscode\extensions\nicolasvuillamy.vscode-groovy-lint-1.7.5\client\node_modules\vscode-languageclient\lib\client.js:2296:18)
    at CallbackList.invoke (d:\Users\cburca\.vscode\extensions\nicolasvuillamy.vscode-groovy-lint-1.7.5\client\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (d:\Users\cburca\.vscode\extensions\nicolasvuillamy.vscode-groovy-lint-1.7.5\client\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at closeHandler (d:\Users\cburca\.vscode\extensions\nicolasvuillamy.vscode-groovy-lint-1.7.5\client\node_modules\vscode-jsonrpc\lib\main.js:240:26)
    at CallbackList.invoke (d:\Users\cburca\.vscode\extensions\nicolasvuillamy.vscode-groovy-lint-1.7.5\client\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (d:\Users\cburca\.vscode\extensions\nicolasvuillamy.vscode-groovy-lint-1.7.5\client\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at IPCMessageReader.fireClose (d:\Users\cburca\.vscode\extensions\nicolasvuillamy.vscode-groovy-lint-1.7.5\client\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
    at ChildProcess.<anonymous> (d:\Users\cburca\.vscode\extensions\nicolasvuillamy.vscode-groovy-lint-1.7.5\client\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
    at ChildProcess.emit (events.js:327:22)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
[Error - 17:30:05] Request textDocument/codeAction failed.`


`Java jre or jdk between 8 and 14 is required `


`GroovyLint: Request cancelled by duplicate call on requestKey`

**Comment by nvuillam** [comment]
What makes you say that it analyzes everything ? :/
npm-groovy-lint is called as a library, with method source code as argument

**Comment by nvuillam** [comment]
So is there still a bug ? ^^

**Comment by cristianburca** [comment]
No. All good. Many thanks.

**Comment by nvuillam** [comment]
Great, thanks for your testing :)
