### ISSUE TITLE
Mac M1 error - codenarcRulesets is Null

### ISSUE THREAD

**Issue by MorAlterya** [nvuillam/vscode-groovy-lint#209]
I do not know if this problem occurs in other Apple silicon.

Logs:
```
Start analyzing file:///Users/bambino.groovy
2024-01-28T12:30:32.453Z npm-groovy-lint <<< NpmGroovyLint.run START >>>
2024-01-28T12:30:32.455Z npm-groovy-lint GroovyLint used config file: /Users/Bobo/checkouts/Babimbo/.groovylintrc
Parse options error: Cannot read properties of null (reading 'codenarcRulesets')
2024-01-28T12:30:32.456Z npm-groovy-lint >>> NpmGroovyLint.run END <<<
===========================================================================
===========================================================================
npm-groovy-lint error: Parse options error: Cannot read properties of null (reading 'codenarcRulesets')
TypeError: Cannot read properties of null (reading 'codenarcRulesets')
    at loadConfig (/Users/Bobo/.vscode/extensions/nicolasvuillamy.vscode-groovy-lint-3.2.0/server/node_modules/npm-groovy-lint/lib/config.js:65:38)
    at async NpmGroovyLint.preProcess (/Users/Bobo/.vscode/extensions/nicolasvuillamy.vscode-groovy-lint-3.2.0/server/node_modules/npm-groovy-lint/lib/groovy-lint.js:154:42)
    at async NpmGroovyLint.run (/Users/Bobo/.vscode/extensions/nicolasvuillamy.vscode-groovy-lint-3.2.0/server/node_modules/npm-groovy-lint/lib/groovy-lint.js:66:27)
If you still have an error, post an issue to get help: https://github.com/nvuillam/vscode-groovy-lint/issues
===========================================================================
===========================================================================
```

Could you please take a look? It seems like a new error, not like the old one with M1 macs.
Using the latest version of the plugin - 3.2.0
Latest MacOS version - Sonoma 14.2.1 (23C71)

**Comment by nvuillam** [comment]
@MorAlterya  I think it's not related to Mac M1 :)

Please can you try to rename `.groovylintrc` into `.groovylintrc.json` ?

**Comment by MorAlterya** [comment]
> @MorAlterya I think it's not related to Mac M1 :)
> 
> Please can you try to rename `.groovylintrc` into `.groovylintrc.json` ?

That was it!
Thank youuuuu!!!
Finally I can enjoy the plugin on the work laptop :D

**Comment by nvuillam** [comment]
Glad your problem is solved :)
