### ISSUE TITLE
Fatal error while calling CodeNarc

### ISSUE THREAD

**Issue by lbourgeois76** [nvuillam/vscode-groovy-lint#54]
If you still have an error, post an issue to get help: https://github.com/nvuillam/vscode-groovy-lint/issues
===========================================================================
===========================================================================
2020-06-16T07:39:31.426Z npm-groovy-lint Analytics sent: module-lint {"app":"npm-groovy-lint","appVersion":"5.1.0","osPlatform":"win32","osRelease":"6.1.7601","ci":false,"status":2,"error":{"msg":"Fatal error while calling CodeNarc\nReason: unknown\n"},"elapsedTimeMs":3406,"rulesets":"C:\\Users\\A350025\\AppData\\Local\\Temp\\npm-groovy-lint\\codeNarcTmpRs_0.8784541535716262.groovy","optionPath":".","optionFiles":"d:\\A350025\\git_dir\\jenkins-shared-libraries\\vars\\edgeBusinessObjectTemplate.groovy","optionParse":true,"optionOutput":"none","optionConfig":"d:\\A350025\\git_dir"}
2020-06-16T07:39:31.436Z npm-groovy-lint Removed temp file C:\Users\A350025\AppData\Local\Temp\npm-groovy-lint\codeNarcTmpDir_0.3940666547410756\edgeBusinessObjectTemplate.groovy as it is not longer used
2020-06-16T07:39:31.437Z npm-groovy-lint Removed temp RuleSet file C:\Users\A350025\AppData\Local\Temp\npm-groovy-lint\codeNarcTmpRs_0.8784541535716262.groovy as it is not longer used
VsCode Groovy Lint error: Cannot read property 'title' of null
TypeError: Cannot read property 'title' of null
    at Object.<anonymous> (d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\out\linter.js:211:29)
    at Generator.next (<anonymous>)
    at fulfilled (d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\out\linter.js:5:58)
2020-06-16T07:39:35.231Z vscode-groovy-lint Error processing file:///d%3A/A350025/git_dir/jenkins-shared-libraries/vars/edgeBusinessObjectTemplate.groovyCannot read property 'title' of null
TypeError: Cannot read property 'title' of null
    at Object.<anonymous> (d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\out\linter.js:211:29)
    at Generator.next (<anonymous>)
    at fulfilled (d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\out\linter.js:5:58)

**Comment by lbourgeois76** [comment]
Info VSCODE:
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.1.7601

**Comment by nvuillam** [comment]
What is your java version ?

Le mar. 16 juin 2020 à 09:45, lbourgeois76 <notifications@github.com> a
écrit :

**Comment by lbourgeois76** [comment]
C:\Users\A350025>java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

**Comment by nvuillam** [comment]
Please can you activate groovyLing.debug in vs code settings and send me
the new log ?

Le mar. 16 juin 2020 à 10:16, lbourgeois76 <notifications@github.com> a
écrit :

**Comment by lbourgeois76** [comment]
===========================================================================
===========================================================================
npm-groovy-lint error: Fatal error while calling CodeNarc
Reason: unknown

undefined
If you still have an error, post an issue to get help: https://github.com/nvuillam/vscode-groovy-lint/issues
===========================================================================
===========================================================================
2020-06-16T09:32:26.861Z npm-groovy-lint Analytics sent: module-lint {"app":"npm-groovy-lint","appVersion":"5.1.0","osPlatform":"win32","osRelease":"6.1.7601","ci":false,"status":2,"error":{"msg":"Fatal error while calling CodeNarc\nReason: unknown\n"},"elapsedTimeMs":6153,"rulesets":"C:\\Users\\A350025\\AppData\\Local\\Temp\\npm-groovy-lint\\codeNarcTmpRs_0.5124655755851897.groovy","optionPath":".","optionFiles":"d:\\A350025\\git_dir\\jenkins-shared-libraries\\vars\\edgeBusinessObjectTemplate.groovy","optionParse":true,"optionOutput":"none","optionConfig":"d:\\A350025\\git_dir"}
2020-06-16T09:32:26.882Z npm-groovy-lint Removed temp file C:\Users\A350025\AppData\Local\Temp\npm-groovy-lint\codeNarcTmpDir_0.2179561041092415\edgeBusinessObjectTemplate.groovy as it is not longer used
2020-06-16T09:32:26.883Z npm-groovy-lint Removed temp RuleSet file C:\Users\A350025\AppData\Local\Temp\npm-groovy-lint\codeNarcTmpRs_0.5124655755851897.groovy as it is not longer used
VsCode Groovy Lint error: Cannot read property 'title' of null
TypeError: Cannot read property 'title' of null
    at Object.<anonymous> (d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\out\linter.js:211:29)
    at Generator.next (<anonymous>)
    at fulfilled (d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\out\linter.js:5:58)
2020-06-16T09:33:00.791Z vscode-groovy-lint Error processing file:///d%3A/A350025/git_dir/jenkins-shared-libraries/vars/edgeBusinessObjectTemplate.groovyCannot read property 'title' of null
TypeError: Cannot read property 'title' of null
    at Object.<anonymous> (d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\out\linter.js:211:29)
    at Generator.next (<anonymous>)
    at fulfilled (d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\out\linter.js:5:58)
2020-06-16T09:33:01.018Z vscode-groovy-lint Save event received for file:///d%3A/A350025/git_dir/jenkins-shared-libraries/vars/edgeBusinessObjectTemplate.groovy
2020-06-16T09:33:03.781Z vscode-groovy-lint Request execute npm-groovy-lint for file:///d%3A/A350025/git_dir/jenkins-shared-libraries/vars/edgeBusinessObjectTemplate.groovy with options {}
2020-06-16T09:33:03.781Z vscode-groovy-lint Reset diagnostics for file:///d%3A/A350025/git_dir/jenkins-shared-libraries/vars/edgeBusinessObjectTemplate.groovy
2020-06-16T09:33:03.782Z vscode-groovy-lint Wait for initial lint request to be completed before running the following ones
Start analyzing file:///d%3A/A350025/git_dir/jenkins-shared-libraries/vars/edgeBusinessObjectTemplate.groovy
2020-06-16T09:35:03.774Z npm-groovy-lint <<< NpmGroovyLint.run START >>>
2020-06-16T09:35:03.811Z npm-groovy-lint GroovyLint used config file: d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\node_modules\npm-groovy-lint\lib\.groovylintrc-recommended.json
2020-06-16T09:35:03.878Z npm-groovy-lint CREATE GROOVY temp file C:\Users\A350025\AppData\Local\Temp\npm-groovy-lint\codeNarcTmpDir_0.4326692775205321\edgeBusinessObjectTemplate.groovy with input source, as CodeNarc requires physical files
2020-06-16T09:35:03.890Z npm-groovy-lint CREATE RULESET tmp file C:\Users\A350025\AppData\Local\Temp\npm-groovy-lint\codeNarcTmpRs_0.3578572026042288.groovy generated from input options, as CodeNarc requires physical files
2020-06-16T09:35:03.891Z npm-groovy-lint CALL CodeNarcServer with {
  "method": "post",
  "url": "http://173.3.68.31:7484/request",
  "data": {
    "codeNarcArgs": "-basedir=C:\\Users\\A350025\\AppData\\Local\\Temp\\npm-groovy-lint\\codeNarcTmpDir_0.4326692775205321 -rulesetfiles=file:C:\\Users\\A350025\\AppData\\Local\\Temp\\npm-groovy-lint\\codeNarcTmpRs_0.3578572026042288.groovy -includes=**/edgeBusinessObjectTemplate.groovy -report=xml:C:\\Users\\A350025\\AppData\\Local\\Temp\\npm-groovy-lint\\codeNarcReportXml_0.3416200141284378.xml",
    "parse": true,
    "file": "C:\\Users\\A350025\\AppData\\Local\\Temp\\npm-groovy-lint\\codeNarcTmpDir_0.4326692775205321\\edgeBusinessObjectTemplate.groovy",
    "requestKey": "d:\\A350025\\git_dir\\jenkins-shared-libraries\\vars\\edgeBusinessObjectTemplate.groovy-none"
  },
  "timeout": 600000
}
2020-06-16T09:35:04.894Z npm-groovy-lint ATTEMPT to start CodeNarcServer with -Xms256m -Xmx2048m --server
2020-06-16T09:35:04.896Z java-caller Error while getting embedded java dir C:\Users\A350025\.java-caller\node_modules\node-jre\jre: ENOENT: no such file or directory, scandir 'C:\Users\A350025\.java-caller\node_modules\node-jre\jre'
2020-06-16T09:35:04.897Z java-caller Java command: java -Xms256m -Xmx2048m -cp d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\node_modules\npm-groovy-lint\lib\java\CodeNarcServer.jar;d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\node_modules\npm-groovy-lint\lib\java\* com.nvuillam.CodeNarcServer --server
Unable to run java command: {"status":1,"stdout":"","stderr":""}
2020-06-16T09:35:05.420Z npm-groovy-lint CALL CodeNarcJava with -Xms256m -Xmx2048m -basedir=C:\Users\A350025\AppData\Local\Temp\npm-groovy-lint\codeNarcTmpDir_0.4326692775205321 -rulesetfiles=file:C:\Users\A350025\AppData\Local\Temp\npm-groovy-lint\codeNarcTmpRs_0.3578572026042288.groovy -includes=**/edgeBusinessObjectTemplate.groovy -report=xml:C:\Users\A350025\AppData\Local\Temp\npm-groovy-lint\codeNarcReportXml_0.3416200141284378.xml
2020-06-16T09:35:05.421Z java-caller Error while getting embedded java dir C:\Users\A350025\.java-caller\node_modules\node-jre\jre: ENOENT: no such file or directory, scandir 'C:\Users\A350025\.java-caller\node_modules\node-jre\jre'
2020-06-16T09:35:05.421Z java-caller Java command: java -Xms256m -Xmx2048m -cp d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\node_modules\npm-groovy-lint\lib\java\CodeNarcServer.jar;d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\node_modules\npm-groovy-lint\lib\java\* com.nvuillam.CodeNarcServer -basedir=C:\Users\A350025\AppData\Local\Temp\npm-groovy-lint\codeNarcTmpDir_0.4326692775205321 -rulesetfiles=file:C:\Users\A350025\AppData\Local\Temp\npm-groovy-lint\codeNarcTmpRs_0.3578572026042288.groovy -includes=**/edgeBusinessObjectTemplate.groovy -report=xml:C:\Users\A350025\AppData\Local\Temp\npm-groovy-lint\codeNarcReportXml_0.3416200141284378.xml
2020-06-16T09:35:05.945Z npm-groovy-lint Error calling CodeNarcServer via java: {"status":1,"stdout":"Error occurred during initialization of VM\nCould not reserve enough space for 2097152KB object heap\n","stderr":""}
2020-06-16T09:35:05.945Z npm-groovy-lint CALL CodeNarcJava with -Xms256m -Xmx2048m -basedir=C:\Users\A350025\AppData\Local\Temp\npm-groovy-lint\codeNarcTmpDir_0.4326692775205321 -rulesetfiles=file:C:\Users\A350025\AppData\Local\Temp\npm-groovy-lint\codeNarcTmpRs_0.3578572026042288.groovy -includes=**/edgeBusinessObjectTemplate.groovy -report=xml:C:\Users\A350025\AppData\Local\Temp\npm-groovy-lint\codeNarcReportXml_0.3416200141284378.xml
2020-06-16T09:35:05.946Z java-caller Error while getting embedded java dir C:\Users\A350025\.java-caller\node_modules\node-jre\jre: ENOENT: no such file or directory, scandir 'C:\Users\A350025\.java-caller\node_modules\node-jre\jre'
2020-06-16T09:35:05.947Z java-caller Java command: java -Xms256m -Xmx2048m -cp d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\node_modules\npm-groovy-lint\lib\java\CodeNarc-1.5.jar;d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\node_modules\npm-groovy-lint\lib\java\groovy\lib\groovy-3.0.3.jar;d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\node_modules\npm-groovy-lint\lib\java\groovy\lib\groovy-templates-3.0.3.jar;d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\node_modules\npm-groovy-lint\lib\java\groovy\lib\groovy-xml-3.0.3.jar;d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\node_modules\npm-groovy-lint\lib\java\groovy\lib\groovy-json-3.0.3.jar;d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\node_modules\npm-groovy-lint\lib\java\slf4j-api-1.7.9.jar;d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\node_modules\npm-groovy-lint\lib\java\log4j-slf4j-impl-2.13.0.jar;d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\node_modules\npm-groovy-lint\lib\java\log4j-api-2.13.0.jar;d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\node_modules\npm-groovy-lint\lib\java\log4j-core-2.13.0.jar;d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\node_modules\npm-groovy-lint\lib\java\GMetrics-0.7.jar;d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\node_modules\npm-groovy-lint\lib\java\* org.codenarc.CodeNarc -basedir=C:\Users\A350025\AppData\Local\Temp\npm-groovy-lint\codeNarcTmpDir_0.4326692775205321 -rulesetfiles=file:C:\Users\A350025\AppData\Local\Temp\npm-groovy-lint\codeNarcTmpRs_0.3578572026042288.groovy -includes=**/edgeBusinessObjectTemplate.groovy -report=xml:C:\Users\A350025\AppData\Local\Temp\npm-groovy-lint\codeNarcReportXml_0.3416200141284378.xml
GroovyLint: Error running CodeNarc: 

2020-06-16T09:35:07.264Z npm-groovy-lint Analytics init: module-lint
2020-06-16T09:35:07.264Z npm-groovy-lint >>> NpmGroovyLint.run END <<<
===========================================================================
===========================================================================
npm-groovy-lint error: Fatal error while calling CodeNarc
Reason: unknown

undefined
If you still have an error, post an issue to get help: https://github.com/nvuillam/vscode-groovy-lint/issues
===========================================================================
===========================================================================
2020-06-16T09:35:07.286Z npm-groovy-lint Analytics sent: module-lint {"app":"npm-groovy-lint","appVersion":"5.1.0","osPlatform":"win32","osRelease":"6.1.7601","ci":false,"status":2,"error":{"msg":"Fatal error while calling CodeNarc\nReason: unknown\n"},"elapsedTimeMs":3439,"rulesets":"C:\\Users\\A350025\\AppData\\Local\\Temp\\npm-groovy-lint\\codeNarcTmpRs_0.3578572026042288.groovy","optionPath":".","optionFiles":"d:\\A350025\\git_dir\\jenkins-shared-libraries\\vars\\edgeBusinessObjectTemplate.groovy","optionParse":true,"optionOutput":"none","optionConfig":"d:\\A350025\\git_dir"}
2020-06-16T09:35:07.287Z npm-groovy-lint Removed temp file C:\Users\A350025\AppData\Local\Temp\npm-groovy-lint\codeNarcTmpDir_0.4326692775205321\edgeBusinessObjectTemplate.groovy as it is not longer used
2020-06-16T09:35:07.288Z npm-groovy-lint Removed temp RuleSet file C:\Users\A350025\AppData\Local\Temp\npm-groovy-lint\codeNarcTmpRs_0.3578572026042288.groovy as it is not longer used
VsCode Groovy Lint error: Cannot read property 'title' of null
TypeError: Cannot read property 'title' of null
    at Object.<anonymous> (d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\out\linter.js:211:29)
    at Generator.next (<anonymous>)
    at fulfilled (d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\out\linter.js:5:58)
2020-06-16T09:35:28.629Z vscode-groovy-lint Error processing file:///d%3A/A350025/git_dir/jenkins-shared-libraries/vars/edgeBusinessObjectTemplate.groovyCannot read property 'title' of null
TypeError: Cannot read property 'title' of null
    at Object.<anonymous> (d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\out\linter.js:211:29)
    at Generator.next (<anonymous>)
    at fulfilled (d:\A350025\vscode-portable\data\extensions\nicolasvuillamy.vscode-groovy-lint-0.16.4\server\out\linter.js:5:58)

**Comment by lbourgeois76** [comment]
Any news about the subject ?

**Comment by nvuillam** [comment]
Sorry I'm on a big mission in my actual work ^^

After some analysis ... it seems it's a crash because of a lack of memory ( CodeNarc can be resource consuming)

![image](https://user-images.githubusercontent.com/17500430/85040333-f8704f80-b188-11ea-9aa3-59d79dbd284b.png)

Do you have a strong computer ? Lots of applications opened ?

**Comment by gstrong14** [comment]
I am also experiencing the same issue even after closing all the other applications on my computer. I didn't use to have this issue it only started occurring recently.

**Comment by nvuillam** [comment]
I'm sorry, i'm on a super hard commando mission at work, can't look for now
:/

If one of you is a player, he can install the sources and debug ? 😅

**Comment by AntCrow** [comment]
This seems likely to be due to to -Xmx2048 and a 32-bit VM. I can get the same message trying to start a 32-bit VM, while I can start a 64-bit one with several times more - so it's not just an available memory limit.
```
>java -Xms256m -Xmx2048m -version
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
```
Is there a user-accessible way to reduce that number, or is it hard coded?

**Comment by lbourgeois76** [comment]
I confirm it is a memory issue.
If there is on my computer less chrome tab, less program application in background the plugin working fine.
There any possibility to optimise the memory or cpu usage ?

**Comment by nvuillam** [comment]
I already tried that by creating a microservice to avoid to reload jars at every call, it improved performances a lot, but for big files it remains slow...

https://github.com/CodeNarc/CodeNarc/issues/465

If you have ideas to optimize the use of local resources, i'm all ears :)

**Comment by nvuillam** [comment]
You can now override java executable and java arguments :)

![image](https://user-images.githubusercontent.com/17500430/87243513-d50e8c80-c436-11ea-8562-867728fc7ab4.png)
