### ISSUE TITLE
There has been an unexpected error while calling npm-groovy-lint

### ISSUE THREAD

**Issue by hugosergey** [nvuillam/vscode-groovy-lint#57]
Hi,

I'm having an issue. Im not sure what is causing it. It was linting correctly but then the error in the subject started appearing. 

I would really appreciate your kind help:

![image](https://user-images.githubusercontent.com/167720/85353367-ac494600-b4cd-11ea-8917-8d023332985a.png)

![image](https://user-images.githubusercontent.com/167720/85353271-71dfa900-b4cd-11ea-8891-c90d8b59930d.png)

`Start analyzing file:///c%3A/Users/Hugosergey/git/TrainingDev/Groovy/Basic%20syntax/01%20HelloWorld.groovy
GroovyLint: Started CodeNarc Server
CodeNarcServer unexpected error:
{
  "message": "Request failed with status code 500",
  "name": "Error",
  "stack": "Error: Request failed with status code 500\n    at createError (c:\\Users\\Hugosergey\\.vscode\\extensions\\nicolasvuillamy.vscode-groovy-lint-0.16.4\\server\\node_modules\\axios\\lib\\core\\createError.js:16:15)\n    at settle (c:\\Users\\Hugosergey\\.vscode\\extensions\\nicolasvuillamy.vscode-groovy-lint-0.16.4\\server\\node_modules\\axios\\lib\\core\\settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (c:\\Users\\Hugosergey\\.vscode\\extensions\\nicolasvuillamy.vscode-groovy-lint-0.16.4\\server\\node_modules\\axios\\lib\\adapters\\http.js:236:11)\n    at IncomingMessage.emit (events.js:208:15)\n    at endReadableNT (_stream_readable.js:1168:12)\n    at processTicksAndRejections (internal/process/task_queues.js:77:11)",
  "config": {
    "url": "http://192.168.0.25:7484/request",
    "method": "post",
    "data": "{\"codeNarcArgs\":\"-basedir=C:\\\\Users\\\\HUGOSE~1\\\\AppData\\\\Local\\\\Temp\\\\npm-groovy-lint\\\\codeNarcTmpDir_0.09585321183587192 -rulesetfiles=file:C:\\\\Users\\\\HUGOSE~1\\\\AppData\\\\Local\\\\Temp\\\\npm-groovy-lint\\\\codeNarcTmpRs_0.29814126045956746.groovy -includes=**/01 HelloWorld.groovy -report=xml:C:\\\\Users\\\\HUGOSE~1\\\\AppData\\\\Local\\\\Temp\\\\npm-groovy-lint\\\\codeNarcReportXml_0.04039041630317253.xml\",\"parse\":true,\"file\":\"C:\\\\Users\\\\HUGOSE~1\\\\AppData\\\\Local\\\\Temp\\\\npm-groovy-lint\\\\codeNarcTmpDir_0.09585321183587192\\\\01 HelloWorld.groovy\",\"requestKey\":\"c:\\\\Users\\\\Hugosergey\\\\git\\\\TrainingDev\\\\Groovy\\\\Basic syntax\\\\01 HelloWorld.groovy-none\"}",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json;charset=utf-8",
      "User-Agent": "axios/0.19.2",
      "Content-Length": 633
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 600000,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1
  }
}
GroovyLint: Error running CodeNarc: 
java.lang.AssertionError: Invalid argument format: [HelloWorld.groovy]. Expression: matcher. Values: matcher = java.util.regex.Matcher[pattern=\-(.*)\=(.*) region=0,17 lastmatch=]
	at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:436)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:670)
	at org.codenarc.CodeNarc$_parseArgs_closure3.doCall(CodeNarc.groovy:195)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1029)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:428)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2124)
	at org.codehaus.groovy.runtime.dgm$195.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:247)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at org.codenarc.CodeNarc.parseArgs(CodeNarc.groovy:192)
	at org.codenarc.CodeNarc.execute(CodeNarc.groovy:146)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at org.codenarc.CodeNarc.main(CodeNarc.groovy:135)

===========================================================================
===========================================================================
npm-groovy-lint error: Fatal error while calling CodeNarc
Reason: unknown
java.lang.AssertionError: Invalid argument format: [HelloWorld.groovy]. Expression: matcher. Values: matcher = java.util.regex.Matcher[pattern=\-(.*)\=(.*) region=0,17 lastmatch=]
	at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:436)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:670)
	at org.codenarc.CodeNarc$_parseArgs_closure3.doCall(CodeNarc.groovy:195)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1029)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:428)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2124)
	at org.codehaus.groovy.runtime.dgm$195.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:247)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at org.codenarc.CodeNarc.parseArgs(CodeNarc.groovy:192)
	at org.codenarc.CodeNarc.execute(CodeNarc.groovy:146)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at org.codenarc.CodeNarc.main(CodeNarc.groovy:135)

undefined
If you still have an error, post an issue to get help: https://github.com/nvuillam/vscode-groovy-lint/issues
===========================================================================
===========================================================================
`

**Comment by nvuillam** [comment]
Do you have a custom .groovylintrc.json file ? 
If yes, please can you post it here ?
If not , please can you send me your groovy file so I can try to reproduce the issue ? ( nicolas.vuillamy@gmail.com if you do not want to make the code public )

**Comment by nvuillam** [comment]
No response, I assume you don't have the problem anymore :)

Please reopen the issue and reply to my questions if you still have the problem !
