### ISSUE TITLE
Fail to download behind proxy

### ISSUE THREAD

**Issue by UnleashSpirit** [nvuillam/vscode-groovy-lint#87]
Hi, finnaly a groovy linter, thanks !

Unfortunately, I have some problems. It might not be one, I might have missed a setup, if so I apologize.
When I try to lint a file I have this in Groovy Lint output :

```
[1020/111212.766:ERROR:registration_protocol_win.cc(103)] CreateFile: Le fichier sp�cifi� est introuvable. (0x2)
Start analyzing file:///c%3A/Users/[...]/jenkinsfile
Java jre or jdk between 8 and undefined is required 
Installing Java jre 8 in C:\Users\[...]\.java-caller...
VsCode Groovy Lint error: request to https://api.adoptopenjdk.net/v2/info/releases/openjdk8?type=jre&openjdk_impl=hotspot&release=latest&os=windows&arch=x64& failed, reason: unable to get local issuer certificate
FetchError: request to https://api.adoptopenjdk.net/v2/info/releases/openjdk8?type=jre&openjdk_impl=hotspot&release=latest&os=windows&arch=x64& failed, reason: unable to get local issuer certificate
    at ClientRequest.<anonymous> (c:\Users\AC75007654\.vscode\extensions\nicolasvuillamy.vscode-groovy-lint-1.2.8\server\node_modules\node-fetch\lib\index.js:1455:11)
    at ClientRequest.emit (events.js:223:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

I have 3 jdk installed on my computer, 1.6, 1.8 a 11. and jre 1.8. So I don't understand why it says that java is required, on what this message is based ?
Never mind, it can download what it's needed but unfortunately I'm behind a corporate proxy so it fails due to certificate :(

I did not find any workaround yet, any ideas ?

Regards

**Comment by nvuillam** [comment]
what is the result when you type `java -version` ? :)

**Comment by UnleashSpirit** [comment]
```
C:\Users\[...]\Desktop>java -version
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
```

**Comment by nvuillam** [comment]
hmmm strange, as I workaround you can probably target your java11 install in PATH environment variable
I'll try to reproduce the issue and keep you posted

**Comment by nvuillam** [comment]
I can't reproduce this issue, that's really strange :/
Please could you activate debug logs ( in settings, like in this screenshot), then send me the full log ?

![image](https://user-images.githubusercontent.com/17500430/96675611-9197b880-136b-11eb-8d8b-67545d16abb1.png)

![image](https://user-images.githubusercontent.com/17500430/96675673-b724c200-136b-11eb-808c-0a824a40f2e5.png)

**Comment by UnleashSpirit** [comment]
Hi,
Here the debug log.
It's seems to find java : ` java-caller Found default java version 1.80202` but still try to download, strange.
It does not bother me if it want to download, may be params to set proxy (with authentication) ?


```
2020-10-21T06:40:17.007Z vscode-groovy-lint Request execute command {"command":"groovyLint.lint","arguments":[]}
2020-10-21T06:40:35.917Z vscode-groovy-lint Formatting request received from client for file:///c%3A/Users/[...]/Jenkinsfile with params {"textDocument":{"uri":"file:///c%3A/Users/[...]/Jenkinsfile"},"options":{"tabSize":2,"insertSpaces":true}}
2020-10-21T06:40:35.917Z vscode-groovy-lint Added in queue: file:///c%3A/Users/[...]/Jenkinsfile ({"format":true,"applyNow":true})
Start analyzing file:///c%3A/Users/[...]/Jenkinsfile
2020-10-21T06:40:56.257Z npm-groovy-lint <<< NpmGroovyLint.run START >>>
2020-10-21T06:40:56.264Z npm-groovy-lint Error reading package.json file: c:\Users\[...]\package.json
2020-10-21T06:40:56.280Z npm-groovy-lint Error reading package.json file: c:\Users\[...]\package.json
2020-10-21T06:40:56.287Z npm-groovy-lint GroovyLint used config file: c:\Users\[...]\.vscode\extensions\nicolasvuillamy.vscode-groovy-lint-1.2.8\server\node_modules\npm-groovy-lint\lib\.groovylintrc-recommended.json
2020-10-21T06:40:56.295Z npm-groovy-lint CREATE GROOVY temp file C:\Users\[...]\AppData\Local\Temp\npm-groovy-lint\codeNarcTmpDir_0.7850295050516694\Jenkinsfile with input source, as CodeNarc requires physical files
2020-10-21T06:40:56.309Z npm-groovy-lint CREATE RULESET tmp file C:\Users\[...]\AppData\Local\Temp\npm-groovy-lint\codeNarcTmpRs_0.2681350464801966.groovy generated from input options, as CodeNarc requires physical files
2020-10-21T06:40:56.309Z npm-groovy-lint CALL CodeNarcServer with {
  "method": "post",
  "url": "http://localhost:7484/request",
  "data": {
    "codeNarcArgs": "-basedir=C:\\Users\\[...]\\AppData\\Local\\Temp\\npm-groovy-lint\\codeNarcTmpDir_0.7850295050516694 -rulesetfiles=file:C:\\Users\\[...]\\AppData\\Local\\Temp\\npm-groovy-lint\\codeNarcTmpRs_0.2681350464801966.groovy -includes=**/Jenkinsfile -report=json:stdout",
    "codeNarcBaseDir": "C:\\Users\\[...]\\AppData\\Local\\Temp\\npm-groovy-lint\\codeNarcTmpDir_0.7850295050516694",
    "codeNarcIncludes": "**/Jenkinsfile",
    "parse": true,
    "file": "C:\\Users\\[...]\\AppData\\Local\\Temp\\npm-groovy-lint\\codeNarcTmpDir_0.7850295050516694\\Jenkinsfile",
    "requestKey": "c:\\Users\\[...]\\Jenkinsfile-none"
  },
  "timeout": 600000
}
2020-10-21T06:40:57.314Z npm-groovy-lint ATTEMPT to start CodeNarcServer with --server
2020-10-21T06:40:57.479Z java-caller Found default java version 1.80202
Java jre or jdk between 8 and undefined is required 
Installing Java jre 8 in C:\Users\[...]\.java-caller...
VsCode Groovy Lint error: request to https://api.adoptopenjdk.net/v2/info/releases/openjdk8?type=jre&openjdk_impl=hotspot&release=latest&os=windows&arch=x64& failed, reason: unable to get local issuer certificate
FetchError: request to https://api.adoptopenjdk.net/v2/info/releases/openjdk8?type=jre&openjdk_impl=hotspot&release=latest&os=windows&arch=x64& failed, reason: unable to get local issuer certificate
    at ClientRequest.<anonymous> (c:\Users\[...]\.vscode\extensions\nicolasvuillamy.vscode-groovy-lint-1.2.8\server\node_modules\node-fetch\lib\index.js:1455:11)
    at ClientRequest.emit (events.js:223:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
2020-10-21T06:40:57.591Z vscode-groovy-lint Error processing file:///c%3A/Users/[...]/Jenkinsfilerequest to https://api.adoptopenjdk.net/v2/info/releases/openjdk8?type=jre&openjdk_impl=hotspot&release=latest&os=windows&arch=x64& failed, reason: unable to get local issuer certificate
FetchError: request to https://api.adoptopenjdk.net/v2/info/releases/openjdk8?type=jre&openjdk_impl=hotspot&release=latest&os=windows&arch=x64& failed, reason: unable to get local issuer certificate
    at ClientRequest.<anonymous> (c:\Users\[...]\.vscode\extensions\nicolasvuillamy.vscode-groovy-lint-1.2.8\server\node_modules\node-fetch\lib\index.js:1455:11)
    at ClientRequest.emit (events.js:223:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
2020-10-21T06:40:57.592Z vscode-groovy-lint Run queued lint for file:///c%3A/Users/[...]/Jenkinsfile ({"format":true,"applyNow":true})
2020-10-21T06:40:57.592Z vscode-groovy-lint Request execute npm-groovy-lint for file:///c%3A/Users/[...]/Jenkinsfile with options {"format":true,"applyNow":true}
2020-10-21T06:40:57.592Z vscode-groovy-lint Reset diagnostics for file:///c%3A/Users/[...]/Jenkinsfile
2020-10-21T06:40:57.592Z vscode-groovy-lint Wait for initial lint request to be completed before running the following ones
```

**Comment by UnleashSpirit** [comment]
What is the content of the `~/.java-caller` folder ?
May be as a workaround I can put what he want inside ? Just java.exe ?

**Comment by nvuillam** [comment]
Thanks for the log, it should help investigate 👍

Meanwhile, if you are on Windows you can force the path to the java version used in settings:

![image](https://user-images.githubusercontent.com/17500430/96693873-08db4580-1388-11eb-8680-722b7b563ef4.png)

**Comment by nvuillam** [comment]
That's kind of crazy .... I tried to reproduce the problem with the exact code, and ... I have 8.202 , not 1.8 like in your log...

![image](https://user-images.githubusercontent.com/17500430/96694702-11804b80-1389-11eb-8b7a-ce9c3bc7eea7.png)

**Comment by nvuillam** [comment]
Found it :)
vscode-groovy-lint uses npm-groovy-lint which uses node-java-caller

node-java-caller 2.2.4 fixed this bug , but npm-groovy-lint contains 2.2.2 :)
I'll make the updates and notify you :)

**Comment by UnleashSpirit** [comment]
Ok, I'll wait the update so I don't use the workaround and can tell if it works ;)

**Comment by nvuillam** [comment]
uploading.... :)

**Comment by nvuillam** [comment]
Uploaded :)
Wait for some minutes, it should be updated automatically (and you'll have to restart VsCode)
Sometimes updates take some time to be available (maybe 10 - 15mn)

You need version **1.2.9** :)

![image](https://user-images.githubusercontent.com/17500430/96698931-f6640a80-138d-11eb-9252-d3028f44cdb5.png)

**Comment by UnleashSpirit** [comment]
Installed, works !
`2020-10-21T09:27:18.951Z java-caller Found default java version 8.202`
Now my already working jenkinsfile is a fu***** christmas tree :D:D
Need to make my own rules.

Thanks !

PS: May be still looking to DL behind a proxy for those who don't have required java version ?

**Comment by nvuillam** [comment]
Glad it works well now, thanks for reporting the issue ;)

ps: the problem is in your corporate proxy config, can't help ;)
