### ISSUE TITLE
There has been an unexpected error while calling npm-groovy-lint. Please join the end of the logs in Output/GroovyLint if you report the issue

### ISSUE THREAD

**Issue by ajay-kakumanu-ghub** [nvuillam/vscode-groovy-lint#93]
Dear Team, 
I am getting an error when i use VS code.
"There has been an unexpected error while calling npm-groovy-lint. Please join the end of the logs in Output/GroovyLint if you report the issue"
I did "Don't display again" but it still showing the same error. Is there any solution for these type errors?

**Comment by nvuillam** [comment]
Please could you join the log ?

**Comment by ajay-kakumanu-by** [comment]
How can I get the logs?

**Comment by gchianes** [comment]
I've been having the same issue.  It seems to have started after I upgraded the MacOS version 10.15.7 (Catalina) several weeks ago, but that could be coincidental.  I've re-installed npm-groovy-lint and have the same issue.  I searched for 'groovylint' in MacOS Finder and found several logs.  

The latest logs say 
2020-11-18T18:54:37.610Z vscode-groovy-lint change configuration event received: restart server and lint again all open documents
2020-11-18T18:54:37.611Z npm-groovy-lint <<< NpmGroovyLint.run START >>>
2020-11-18T18:54:37.617Z npm-groovy-lint GroovyLint used config file: /Users/gchia001/.groovylintrc.js
2020-11-18T18:54:37.620Z npm-groovy-lint Error reading JavaScript file: /Users/gchia001/.groovylintrc.js
Parse options error: Cannot read config file: /Users/gchia001/.groovylintrc.js
Error: Unexpected token ':'
2020-11-18T18:54:37.621Z npm-groovy-lint >>> NpmGroovyLint.run END <<<
2020-11-18T18:56:39.689Z npm-groovy-lint <<< NpmGroovyLint.run START >>>
2020-11-18T18:56:39.692Z npm-groovy-lint GroovyLint used config file: /Users/gchia001/.groovylintrc.js
2020-11-18T18:56:39.695Z npm-groovy-lint Error reading JavaScript file: /Users/gchia001/.groovylintrc.js
Parse options error: Cannot read config file: /Users/gchia001/.groovylintrc.js
Error: Unexpected token ':'
2020-11-18T18:56:39.695Z npm-groovy-lint >>> NpmGroovyLint.run END <<<

I renamed the file from .groovylintrc.js to .groovylintrc.json and the problem seems to have disappeared.  It could be a totally different root cause from Ajay's issue.  I do see this one error in the new log:

2020-11-18T19:40:21.471Z vscode-groovy-lint Provided 4 codeActions for file:///Users/gchia001/src/pipelinelibs/vars/checkmarx.groovy
(node:58013) UnhandledPromiseRejectionWarning: Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:223:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)
(node:58013) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)

Any idea what server it's reaching out to for Groovy/Lint?

**Comment by gchianes** [comment]
I found it in the log (should have spent more time looking before I asked!):

2020-11-18T19:40:09.120Z npm-groovy-lint ATTEMPT to start CodeNarcServer with --server
2020-11-18T19:40:10.012Z java-caller Found default java version 15.01
2020-11-18T19:40:10.012Z java-caller Java command: java -Xms256m -Xmx2048m -cp /Users/gchia001/.vscode/extensions/nicolasvuillamy.vscode-groovy-lint-1.3.0/server/node_modules/npm-groovy-lint/lib/java/CodeNarcServer.jar:/Users/gchia001/.vscode/extensions/nicolasvuillamy.vscode-groovy-lint-1.3.0/server/node_modules/npm-groovy-lint/lib/java/* com.nvuillam.CodeNarcServer --server
2020-11-18T19:40:12.787Z npm-groovy-lint SUCCESS: CodeNarcServer is running
GroovyLint: Started CodeNarc Server

**Comment by nvuillam** [comment]
I'm pretty sure that there is an issue in your .groovylintrc.js file :) 

```
Parse options error: Cannot read config file: /Users/gchia001/.groovylintrc.js
Error: Unexpected token ':'
```

**Comment by nvuillam** [comment]
oops I read too fast :)

npm-groovy-lint tries to reach a local CodeNarc Server
But as it is on locahost (and reachable from locahost only) , I don't see why there could be a SSL issue ...

**Comment by tiago-snigel** [comment]
Hi guys, I have the exact same issue, tried to disable the Insights in VsCode settings but nothing changed, and the error persists.

Unable to run java command: {"status":1,"stdout":"","stderr":"","childJavaProcess":{"_events":{},"_eventsCount":2,"_closesNeeded":1,"_closesGot":1,"connected":false,"signalCode":null,"exitCode":1,"killed":false,"spawnfile":"java","_handle":null,"spawnargs":["java","-Xms256m","-Xmx2048m","-cp","\"c:\\Users\\Tiago\\.vscode\\extensions\\nicolasvuillamy.vscode-groovy-lint-1.3.0\\server\\node_modules\\npm-groovy-lint\\lib\\java\\CodeNarcServer.jar;c:\\Users\\Tiago\\.vscode\\extensions\\nicolasvuillamy.vscode-groovy-lint-1.3.0\\server\\node_modules\\npm-groovy-lint\\lib\\java\\*\"","com.nvuillam.CodeNarcServer","--server"],"pid":7944,"stdin":null,"stdout":null,"stderr":null,"stdio":[null,null,null]}}
GroovyLint: Error running CodeNarc: 

npm-groovy-lint error: Fatal error while calling CodeNarc
Reason: unknown

undefined
If you still have an error, post an issue to get help: https://github.com/nvuillam/vscode-groovy-lint/issues

**Comment by whephner** [comment]
I have the CodeNarc errors as well, turned off insights still getting it. below is the output:

npm-groovy-lint error: Fatal error while calling CodeNarc
Reason: unknown
java.lang.AssertionError: Invalid argument format: [Project]. Expression: matcher. Values: matcher = java.util.regex.Matcher[pattern=\-(.*)\=(.*) region=0,7 lastmatch=]
	at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:438)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:670)
	at org.codenarc.CodeNarc$_parseArgs_closure3.doCall(CodeNarc.groovy:222)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1026)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:428)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2124)
	at org.codehaus.groovy.runtime.dgm$195.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:247)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at org.codenarc.CodeNarc.parseArgs(CodeNarc.groovy:219)
	at org.codenarc.CodeNarc.execute(CodeNarc.groovy:167)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at org.codenarc.CodeNarc.main(CodeNarc.groovy:156)

**Comment by TAGC** [comment]
Just installed this plugin and tried to format a Jenkinsfile. I get this error when opening the Jenkinsfile:

> Start analyzing file:///c%3A/Projects/sales-commissions/resources/jenkins-files/Jenkinsfile-jobsapi-deploy-dev-Multibranch
Unable to run java command: {"status":1,"stdout":"","stderr":"","childJavaProcess":{"_events":{},"_eventsCount":2,"_closesNeeded":1,"_closesGot":1,"connected":false,"signalCode":null,"exitCode":1,"killed":false,"spawnfile":"java","_handle":null,"spawnargs":["java","-Xms256m","-Xmx2048m","-cp","\"c:\\Users\\e0065186\\.vscode\\extensions\\nicolasvuillamy.vscode-groovy-lint-1.4.0\\server\\node_modules\\npm-groovy-lint\\lib\\java\\CodeNarcServer.jar;c:\\Users\\e0065186\\.vscode\\extensions\\nicolasvuillamy.vscode-groovy-lint-1.4.0\\server\\node_modules\\npm-groovy-lint\\lib\\java\\*\"","com.nvuillam.CodeNarcServer","--server"],"pid":12924,"stdin":null,"stdout":null,"stderr":null,"stdio":[null,null,null]}}
GroovyLint: Error running CodeNarc: 

===========================================================================
===========================================================================
npm-groovy-lint error: Fatal error while calling CodeNarc
Reason: unknown

undefined
If you still have an error, post an issue to get help: https://github.com/nvuillam/vscode-groovy-lint/issues
===========================================================================
===========================================================================

**Comment by jsolas** [comment]
I have this same problem, here is my log, please help:

> npm-groovy-lint error: Parse options error: Cannot read config file: /Users/jsolas/ctrlit/.groovylintrc.json
> Error: Unexpected end of JSON input
> SyntaxError: Cannot read config file: /Users/jsolas/ctrlit/.groovylintrc.json
> Error: Unexpected end of JSON input
>     at JSON.parse (<anonymous>)
>     at loadJSONConfigFile (/Users/jsolas/.vscode/extensions/nicolasvuillamy.vscode-groovy-lint-1.7.5/server/node_modules/npm-groovy-lint/lib/config.js:221:21)
>     at async loadConfigFromFile (/Users/jsolas/.vscode/extensions/nicolasvuillamy.vscode-groovy-lint-1.7.5/server/node_modules/npm-groovy-lint/lib/config.js:190:32)
>     at async loadConfig (/Users/jsolas/.vscode/extensions/nicolasvuillamy.vscode-groovy-lint-1.7.5/server/node_modules/npm-groovy-lint/lib/config.js:62:22)
>     at async NpmGroovyLint.preProcess (/Users/jsolas/.vscode/extensions/nicolasvuillamy.vscode-groovy-lint-1.7.5/server/node_modules/npm-groovy-lint/lib/groovy-lint.js:129:42)
>     at async NpmGroovyLint.run (/Users/jsolas/.vscode/extensions/nicolasvuillamy.vscode-groovy-lint-1.7.5/server/node_modules/npm-groovy-lint/lib/groovy-lint.js:63:27)

**Comment by MostHated** [comment]
I keep getting:
```sh
[Info  - 12:09:14 PM] Connection to server got closed. Server will restart.
Start analyzing file:///home/mosthated/_dev/languages/groovy/path_test.groovy
Completed analyzing file:///home/mosthated/_dev/languages/groovy/path_test.groovy in 262 ms
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);


[Info  - 12:09:15 PM] Connection to server got closed. Server will restart.
[Error - 12:09:15 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/mosthated/.vscode-insiders/extensions/nicolasvuillamy.vscode-groovy-lint-1.7.5/client/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/mosthated/.vscode-insiders/extensions/nicolasvuillamy.vscode-groovy-lint-1.7.5/client/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/home/mosthated/.vscode-insiders/extensions/nicolasvuillamy.vscode-groovy-lint-1.7.5/client/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/home/mosthated/.vscode-insiders/extensions/nicolasvuillamy.vscode-groovy-lint-1.7.5/client/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/mosthated/.vscode-insiders/extensions/nicolasvuillamy.vscode-groovy-lint-1.7.5/client/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/mosthated/.vscode-insiders/extensions/nicolasvuillamy.vscode-groovy-lint-1.7.5/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/mosthated/.vscode-insiders/extensions/nicolasvuillamy.vscode-groovy-lint-1.7.5/client/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/mosthated/.vscode-insiders/extensions/nicolasvuillamy.vscode-groovy-lint-1.7.5/client/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/mosthated/.vscode-insiders/extensions/nicolasvuillamy.vscode-groovy-lint-1.7.5/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/mosthated/.vscode-insiders/extensions/nicolasvuillamy.vscode-groovy-lint-1.7.5/client/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at IPCMessageReader.fireClose (/home/mosthated/.vscode-insiders/extensions/nicolasvuillamy.vscode-groovy-lint-1.7.5/client/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/home/mosthated/.vscode-insiders/extensions/nicolasvuillamy.vscode-groovy-lint-1.7.5/client/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (node:events:406:35)
	at maybeClose (node:internal/child_process:1064:16)
	at Socket.<anonymous> (node:internal/child_process:450:11)
	at Socket.emit (node:events:394:28)
	at Pipe.<anonymous> (node:net:672:12)
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);


[Error - 12:09:15 PM] Connection to server got closed. Server will not be restarted.
Unexpected error: connect EHOSTUNREACH 0.0.0.17:443
Error: connect EHOSTUNREACH 0.0.0.17:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:16)

...
```

Eventually followed by:

```sh
The Groovy Lint server crashed 5 times in the last 3 minutes. The server will not be restarted.
```

**Comment by nvuillam** [comment]
npm-groovy-lint uses a local GroovyLint server to enhanec performances by avoiding to launch java at each lint request

Please can you check with your antivirus/firewall is there is something blocked at some point ?

**Comment by MostHated** [comment]
I am quite sure that is not an issue at this time. The issue was occurring on my Linux desktop, so I switched over to using Windows on another machine. It worked as expected for about 1-2 minutes, but then after having made multiple quick edits and hitting save a few times it then started having the same issue as my Linux desktop.

**Comment by nvuillam** [comment]
@MostHated i've not looked at the usage stats for ages, that's something I used to detect crashes a looooong time ago, so I'll release a new version with telemetry disabled by default , thanks for the diagnosis !
